# <center>Block 0: Vectors and matrices in numPy</center>
### <center>Alfred Galichon (NYU)</center>
## <center>`math+econ+code' masterclass on optimal transport and economic applications</center>
<center>© 2018-2020 by Alfred Galichon. Support from NSF grant DMS-1716489 is acknowledged.</center>

#### <center>With R code examples</center>

## Vectors and matrices in numPy
* Unlike R or Matlab, Python has no built-in matrix algebra nterface. Fortunately, the numPy library provides powerful matrix capabilities, on par with R or Matlab. Here is a quick introduction to vectorization, operations on vectors and matrices, higher-dimensional arrays, Kronecker products and sparse matrices, etc. in numPy.

* This is *not* a tutorial on Python itself. They are plenty good ones available on the web.


## Vectorization and memory order

* Matrices in all mathematical softwares are represented in a *vectorized* way as a sequence of numbers in the computers memory. This representation can involve either stacking the lines, or stacking the columns.

* Different programming languages can use either of the two stacking conventions:
    + Stacking the lines (Row-major order) is used by C, and is the default convention for for Python (Numpy).
    + Stacking the columns (Column-major order) is used by Fortran, Matlab, R, and most underlying core linear algebra libraries (like BLAS). A $2\times2$ matrix $A$ is then vectorized as $\left(  A_{11},A_{21},A_{12},A_{22}\right)$. Thus, we shall remember that R represents matrices by **varying the first index first**.

First, we load numPy:

In [3]:
import numpy as np

In [6]:
a = np.array([[11,12],[21,22],[31,32]])
a

array([[11, 12],
       [21, 22],
       [31, 32]])

In [7]:
a.shape

(3, 2)

In order to reshape the vector matrix `a`, one modifies its `shape` attribute. The following reshapes the matrix `a` into a row vector. 

In [21]:
    a.shape = 1,6
a

array([[11, 12, 21, 22, 31, 32]])

The previous output evidences the fact that Python uses the row-major order: rows are stacked one after the other. 
To reshape the vector into a column vector, do:

In [22]:
a.shape = 6,1
a

array([[11],
       [12],
       [21],
       [22],
       [31],
       [32]])

Equivalently, one could have set `tst.shape=6,-1`, where Python would replace `-1` in `tst.shape=1,-1` by the integer needed for the formula to make sense (in this case, `1`). 
Another way to reshape is to use the method `reshape,` which returns a duplicate of the object with the requested shape.

In [26]:
a1=np.array(range(6))
a2 = a1.reshape(3,2)
print(a1)
print(a2)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


Note that numPy also supports the column-major order, but you have to specifically ask for it, by passing the optional argument `order='F'`, where 'F' for Fortran.

In [27]:
a3 = np.array(range(6)).reshape(3,2, order='F')
a3

array([[0, 3],
       [1, 4],
       [2, 5]])